language: php
dist: trusty
sudo: true

cache:
  directories:
    - $HOME/.composer

matrix:
  # Don't wait for the allowed failures to build.
  fast_finish: true

before_install:
  - phpenv config-rm xdebug.ini || true

install:
  - npm install gulp -g
  - npm install
  - composer install

script:
  # Default gulp is configured to run coder, csslint and eslint.
  - gulp
